//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""SimsCamera"",
            ""id"": ""c5f5f9d2-271d-40fd-8c57-a99dc24ed3b9"",
            ""actions"": [
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""537d046b-9089-453b-9bc5-162b9e6c80f4"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""f07ae228-e1d9-415c-8d1c-b4d928928b29"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""99cce852-0b04-4111-886d-95ceb5ccf7a0"",
                    ""path"": ""<Keyboard>/#(Q)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""1963514e-7154-446c-a579-ccb5df8f6524"",
                    ""path"": ""<Keyboard>/#(D)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""SimsCursor"",
            ""id"": ""5076dcce-166c-4019-bdf4-61574568eef8"",
            ""actions"": [
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""4af62691-40ff-4791-b72d-ce261bf42263"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""6c1a7069-cf16-4f3d-85a1-5c0f7e996def"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""21ebaea8-be0b-483c-8926-233d1e26d880"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cefd1e73-8d31-4c2b-8cef-8bfa332911f7"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a489783-22b7-466f-9449-05d55015e588"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""2e8dd504-ecb9-4cdd-85c0-8c6662274331"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""df4f5c2f-1588-4d09-a7f3-96ac5d579656"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""730ce2e9-f0a7-4af3-9040-d75010021147"",
                    ""path"": ""<Keyboard>/#(E)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SimsCamera
        m_SimsCamera = asset.FindActionMap("SimsCamera", throwIfNotFound: true);
        m_SimsCamera_Rotate = m_SimsCamera.FindAction("Rotate", throwIfNotFound: true);
        // SimsCursor
        m_SimsCursor = asset.FindActionMap("SimsCursor", throwIfNotFound: true);
        m_SimsCursor_MousePosition = m_SimsCursor.FindAction("MousePosition", throwIfNotFound: true);
        m_SimsCursor_Select = m_SimsCursor.FindAction("Select", throwIfNotFound: true);
        m_SimsCursor_Rotate = m_SimsCursor.FindAction("Rotate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SimsCamera
    private readonly InputActionMap m_SimsCamera;
    private List<ISimsCameraActions> m_SimsCameraActionsCallbackInterfaces = new List<ISimsCameraActions>();
    private readonly InputAction m_SimsCamera_Rotate;
    public struct SimsCameraActions
    {
        private @Controls m_Wrapper;
        public SimsCameraActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Rotate => m_Wrapper.m_SimsCamera_Rotate;
        public InputActionMap Get() { return m_Wrapper.m_SimsCamera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SimsCameraActions set) { return set.Get(); }
        public void AddCallbacks(ISimsCameraActions instance)
        {
            if (instance == null || m_Wrapper.m_SimsCameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SimsCameraActionsCallbackInterfaces.Add(instance);
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
        }

        private void UnregisterCallbacks(ISimsCameraActions instance)
        {
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
        }

        public void RemoveCallbacks(ISimsCameraActions instance)
        {
            if (m_Wrapper.m_SimsCameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISimsCameraActions instance)
        {
            foreach (var item in m_Wrapper.m_SimsCameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SimsCameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SimsCameraActions @SimsCamera => new SimsCameraActions(this);

    // SimsCursor
    private readonly InputActionMap m_SimsCursor;
    private List<ISimsCursorActions> m_SimsCursorActionsCallbackInterfaces = new List<ISimsCursorActions>();
    private readonly InputAction m_SimsCursor_MousePosition;
    private readonly InputAction m_SimsCursor_Select;
    private readonly InputAction m_SimsCursor_Rotate;
    public struct SimsCursorActions
    {
        private @Controls m_Wrapper;
        public SimsCursorActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MousePosition => m_Wrapper.m_SimsCursor_MousePosition;
        public InputAction @Select => m_Wrapper.m_SimsCursor_Select;
        public InputAction @Rotate => m_Wrapper.m_SimsCursor_Rotate;
        public InputActionMap Get() { return m_Wrapper.m_SimsCursor; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SimsCursorActions set) { return set.Get(); }
        public void AddCallbacks(ISimsCursorActions instance)
        {
            if (instance == null || m_Wrapper.m_SimsCursorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SimsCursorActionsCallbackInterfaces.Add(instance);
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
        }

        private void UnregisterCallbacks(ISimsCursorActions instance)
        {
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
        }

        public void RemoveCallbacks(ISimsCursorActions instance)
        {
            if (m_Wrapper.m_SimsCursorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISimsCursorActions instance)
        {
            foreach (var item in m_Wrapper.m_SimsCursorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SimsCursorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SimsCursorActions @SimsCursor => new SimsCursorActions(this);
    public interface ISimsCameraActions
    {
        void OnRotate(InputAction.CallbackContext context);
    }
    public interface ISimsCursorActions
    {
        void OnMousePosition(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
    }
}
